version: '3'
services:
  jupyter-service:
    image: python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:8888"
      - "6000:6006"
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /Users/laszlofreund/:/mnt
    entrypoint: ./start_jupyter.sh
    tty: true # for interactive bash