version: '3'
services:
  jupyter-service:
    build:
      context: ../
      dockerfile: config_docker/Dockerfile
    ports:
      - "8880:8888"  # jupyter
      - "6000:6006"  # tensorboard
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./mnt/:/mnt
    tty: true # for interactive bash